#!/bin/bash

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}--- RFSight Installer ---${NC}"

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}[ERROR] Python 3 is not installed. Please install it to proceed.${NC}"
    exit 1
fi

# Create and Setup Virtual Environment
echo -e "${BLUE}[INFO] Setting up Python Virtual Environment (backend/venv)...${NC}"

if [ ! -d "backend/venv" ]; then
    python3 -m venv backend/venv
    if [ $? -ne 0 ]; then
        echo -e "${RED}[ERROR] Failed to create virtual environment. Please install 'python3-venv'.${NC}"
        exit 1
    fi
fi

source backend/venv/bin/activate

echo -e "${BLUE}[INFO] Installing dependencies from backend/requirements.txt...${NC}"
# Upgrade pip and install requirements
pip install --upgrade pip &> /dev/null
pip install -r backend/requirements.txt &> /dev/null
pip install bcrypt &> /dev/null

if [ $? -ne 0 ]; then
    echo -e "${RED}[ERROR] Failed to install dependencies. Check your internet connection or requirements.txt.${NC}"
    exit 1
fi

echo -e "${BLUE}[INFO] Generating security keys and password hashes...${NC}"
SECRET_KEY=$(openssl rand -hex 32)

PASSWORD_HASH=$(python3 -c "import bcrypt; print(bcrypt.hashpw(b'Admin@123', bcrypt.gensalt()).decode('utf-8'))")

# Create Backend .env
echo -e "${BLUE}[INFO] Creating backend/.env configuration...${NC}"
cat <<EOF > backend/.env
# Auto-generated by install.sh
UI_HOST=ui.rfsight.duckdns.org
API_HOST=0.0.0.0
API_PORT=6792
SECRET_KEY=${SECRET_KEY}
ALGORITHM=HS256

EMAIL_ADDRESS=admin@rfsight.com
EMAIL_PASSWORD=Lock@rfsight.testmail57
EMAIL_SERVER=localhost
EMAIL_PORT=25

# Mongo Settings
MONGODB_HOST=localhost
MONGODB_LOGIN=dbAdmin
MONGODB_PASSWD=.Lock.DBMgAdmin
MONGODB_PORT=27017
MONGODB_DATABASE=rfsight

# Network Interface for ARP Scan (Inside container)
API_CONTAINER_INTERFACE=eth0
EOF

# Create mongo-init.js
echo -e "${BLUE}[INFO] Creating database initialization script...${NC}"
cat <<EOF > backend/src/database/mongo-init/mongo-init.js
// Auto-generated by install.sh
db = db.getSiblingDB('admin');
db.auth(process.env.MONGO_INITDB_ROOT_USERNAME, process.env.MONGO_INITDB_ROOT_PASSWORD);

db = db.getSiblingDB('rfsight');

db.createUser({
    'user': 'dbAdmin',
    'pwd': '.Lock.DBMgAdmin',
    'roles': [{
        'role': 'dbOwner',
        'db': 'rfsight'
    }]
});

var orgId = ObjectId("690d3f7c901bbbf23fab98d0");
var userId = ObjectId("690d3f62901bbbf23fab98cb");
var netId = ObjectId("690d3f91901bbbf23fab98d5");

var now = new Date();
now.setHours(now.getHours() - 3);

db.createCollection("users");
db.createCollection("devices");
db.createCollection("profiles");
db.createCollection("networks");
db.createCollection("organizations");

db.organizations.insertOne({
    _id: orgId,
    name: "Default Org",
    networks: [netId],
    users: [userId],
    createdAt: now,
    updatedAt: now
});

db.networks.insertOne({
    _id: netId,
    name: "Default Network",
    network_type: 'Bridge',
    network_cidr: '15.0.0.0/24',
    location: "Main Office",
    organizationId: orgId,
    devices: [],
    createdAt: now,
    updatedAt: now
});

db.users.insertOne({
    _id: userId,
    username: "root",
    email: "root@rfsight.com",
    firstName: "Root",
    lastName: "RFSight",
    password: "${PASSWORD_HASH}",
    permission: 5,
    organizationId: orgId,
    createdAt: now,
    updatedAt: now
});

print("RFSight Database Initialized with Root User and Default Organization/Network.");
EOF

# Deactivate venv
deactivate

echo -e "${GREEN}[SUCCESS] Environment configured successfully!${NC}"
echo -e "You can now run ${BLUE}./init.sh${NC} to start the application."
