import { Alert } from './alert/alert-config.types';
import { AutoUpdate } from './autoupdate/autoupdate-config.types';
import { DHCP6D } from './dhcp/dhcp6d/dhcp6d-config.types';
import { DHCPD } from './dhcp/dhcpd/dhcpd-config.types';
import { Discovery } from './discovery/discovery-config.types';
import { HTTP } from './http/http-config.types';
import { LedD } from './ledd/ledd-config.types';
import { NTP } from './ntp/ntp-config.types';
import { PingWatchDog } from './pingwatchdog/pingwatchdog-config.types';
import { PPPoERelay } from './pppoerelay/pppoerelay-config.types';
import { QOS } from './qos/qos-config.types';
import { ResetD } from './resetd/resetd-config.types';
import { SNMP } from './snmp/snmp-config.types';
import { SSH } from './ssh/ssh-config.types';
import { TC } from './tc/tc-config.types';
import { Telnet } from './telnet/telnet-config.types';
import { WNMS } from './wnms/wnms-config.types';
import { Zapd } from './zapd/zapd-config.types';

export type Services = {
  snmp: SNMP;
  pppoerelay: PPPoERelay;
  ledd: LedD;
  dhcp6d: DHCP6D;
  resetd: ResetD;
  autoupdate: AutoUpdate;
  http: HTTP;
  wnms: WNMS;
  ssh: SSH;
  pingwatchdog: PingWatchDog;
  dhcpd: DHCPD;
  discovery: Discovery;
  alert: Alert;
  qos: QOS;
  telnet: Telnet;
  zapd: Zapd;
  tc: TC;
  ntp: NTP;
};
