// Auto-generated by install.sh
db = db.getSiblingDB('admin');
db.auth(process.env.MONGO_INITDB_ROOT_USERNAME, process.env.MONGO_INITDB_ROOT_PASSWORD);

db = db.getSiblingDB('rfsight');

db.createUser({
    'user': 'dbAdmin',
    'pwd': '.Lock.DBMgAdmin',
    'roles': [{
        'role': 'dbOwner',
        'db': 'rfsight'
    }]
});

var orgId = ObjectId("690d3f7c901bbbf23fab98d0");
var userId = ObjectId("690d3f62901bbbf23fab98cb");
var netId = ObjectId("690d3f91901bbbf23fab98d5");

var now = new Date();
now.setHours(now.getHours() - 3);

db.createCollection("users");
db.createCollection("devices");
db.createCollection("profiles");
db.createCollection("networks");
db.createCollection("organizations");

db.organizations.insertOne({
    _id: orgId,
    name: "Default Org",
    networks: [netId],
    users: [userId],
    createdAt: now,
    updatedAt: now
});

db.networks.insertOne({
    _id: netId,
    name: "Default Network",
    network_type: 'Bridge',
    network_cidr: '15.0.0.0/24',
    location: "Main Office",
    organizationId: orgId,
    devices: [],
    createdAt: now,
    updatedAt: now
});

db.users.insertOne({
    _id: userId,
    username: "root",
    email: "root@rfsight.com",
    firstName: "Root",
    lastName: "RFSight",
    password: "$2b$12$jpp6qonFoSUq12N82JS.R.aIAac5FQPug2qGhUd1iOR1wpitZOX1S",
    permission: 5,
    organizationId: orgId,
    createdAt: now,
    updatedAt: now
});

print("RFSight Database Initialized with Root User and Default Organization/Network.");
