import {
  Alert,
  Backdrop,
  Box,
  Button,
  CircularProgress,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  SelectChangeEvent,
  TextField,
  Typography,
  useTheme,
} from '@mui/material';
import Joi from 'joi';
import { Dispatch, SetStateAction, useState } from 'react';
import { toast } from 'react-toastify';
import { useAppSelector } from '../hooks';
import { useGetAllOrganizationsQuery } from '../store/slices/organization/organizationApiSlice';
import { useRegisterNewUserMutation } from '../store/slices/user/userApiSlice';
import { selectUserInfo } from '../store/slices/user/userSlice';
import { Permissions } from '../ts/enums';
import { generateRandomPassword, PermissionLabels } from '../ts/helpers';
import { DefaultApiError, IRegisterUserPayload } from '../ts/interfaces';
import {
  EmailSchema,
  FirstNameSchema,
  LastNameSchema,
  RegisterSchema,
  UsernameSchema
} from '../ts/validation';
import { FormPaper } from './styled/FormPaper';

export const UserCreationForm = () => {
  // Hooks
  const theme = useTheme();
  const [registerNewUser, { isLoading }] = useRegisterNewUserMutation();
  const { data: organizationCollection, isLoading: orgsLoading } =
      useGetAllOrganizationsQuery();
  const loggedUserInfo = useAppSelector(selectUserInfo);

  // States
  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [permission, setPermission] = useState('0');
  const [organizationId, setOrganizationId] = useState('');
  const [userCredentialMsg, setUserCredentialMsg] = useState('');

  // Error states
  const [usernameErr, setUsernameErr] = useState('');
  const [emailErr, setEmailErr] = useState('');
  const [firstNameErr, setFirstNameErr] = useState('');
  const [lastNameErr, setLastNameErr] = useState('');
  const [submitErrMsg, setSubmitErrMsg] = useState('');

  // Handlers
  const handleFieldChange = (
    v: string,
    fieldSchema: Joi.Schema,
    setFieldValue: Dispatch<SetStateAction<string>>,
    setFieldErr: Dispatch<SetStateAction<string>>
  ) => {
    setFieldValue(v);
    if (submitErrMsg) setSubmitErrMsg('');

    const { error, value } = fieldSchema.validate(v);

    if (error) {
      setFieldErr(error.message);
    } else {
      setFieldErr('');
    }
    return value;
  };

  const handleSelectOrg = (event: SelectChangeEvent) => {
    setOrganizationId(event.target.value as string);
  };

  const handleSelectPermission = (event: SelectChangeEvent) => {
    setPermission(event.target.value);
  }

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const autogeneratedPassword = generateRandomPassword();
    const registerPayload: IRegisterUserPayload = {
      username,
      email,
      firstName,
      lastName,
      permission: Number(permission),
      password: autogeneratedPassword,
      organizationId,
    };

    const { error: validationError, value } = RegisterSchema.validate({
      ...registerPayload,
      passwordConfirmation: registerPayload.password,
    });

    if (validationError) {
      return setSubmitErrMsg(validationError.message);
    }

    try {
      const registeredNewUser = await registerNewUser(registerPayload).unwrap();
      if (registeredNewUser) {
        toast.success(registeredNewUser.message);
        setUserCredentialMsg(
          'Atenção: Esta senha só será exibida uma vez.\n\n' +
          `Nome de usuário: ${username}\n\n` +
          `Senha gerada: ${autogeneratedPassword}`
        );
      };
      return value;
    } catch (error) {
      const err = error as DefaultApiError;
      setSubmitErrMsg(err.detail.message);
      return false;
    }
  };

  return (
    <FormPaper>
      <Box
        component="form"
        autoComplete="off"
        width="100%"
        onSubmit={handleSubmit}
      >
        {!userCredentialMsg && <>
          <Box display="flex" flexDirection="column">
            <TextField
              id="username"
              label="Nome de usuário"
              variant="outlined"
              fullWidth
              autoFocus
              autoComplete="new-password"
              type="text"
              onChange={(e) =>
                handleFieldChange(
                  e.target.value,
                  UsernameSchema,
                  setUsername,
                  setUsernameErr
                )
              }
              value={username}
              error={usernameErr !== ''}
              required
            />
            <Typography
              variant="caption"
              color={theme.palette.error.main}
              m={0}
              fontSize="small"
              width="100%"
              align="left"
            >
              {usernameErr}
            </Typography>
          </Box>
          <Box display="flex" flexDirection="column">
            <TextField
              id="email"
              label="Endereço de e-mail"
              variant="outlined"
              sx={{ marginTop: '1rem' }}
              fullWidth
              autoComplete="new-password"
              type="email"
              onChange={(e) =>
                handleFieldChange(
                  e.target.value,
                  EmailSchema,
                  setEmail,
                  setEmailErr
                )
              }
              value={email}
              error={emailErr !== ''}
              required
            />
            <Typography
              variant="caption"
              color={theme.palette.error.main}
              m={0}
              fontSize="small"
              align="left"
            >
              {emailErr}
            </Typography>
          </Box>
          <Box display="flex" flexDirection="column">
            <TextField
              id="firstName"
              label="Primeiro nome"
              variant="outlined"
              sx={{ marginTop: '1rem' }}
              fullWidth
              type="text"
              onChange={(e) =>
                handleFieldChange(
                  e.target.value,
                  FirstNameSchema,
                  setFirstName,
                  setFirstNameErr
                )
              }
              value={firstName}
              error={firstNameErr !== ''}
              required
            />
            <Typography
              variant="caption"
              color={theme.palette.error.main}
              m={0}
              fontSize="small"
              align="left"
            >
              {firstNameErr}
            </Typography>
          </Box>
          <Box display="flex" flexDirection="column">
            <TextField
              id="lastName"
              label="Último nome"
              variant="outlined"
              sx={{ marginTop: '1rem' }}
              autoComplete="new-password"
              fullWidth
              type="text"
              onChange={(e) =>
                handleFieldChange(
                  e.target.value,
                  LastNameSchema,
                  setLastName,
                  setLastNameErr
                )
              }
              value={lastName}
              error={lastNameErr !== ''}
              required
            />
            <Typography
              variant="caption"
              color={theme.palette.error.main}
              m={0}
              fontSize="small"
              align="left"
            >
              {lastNameErr}
            </Typography>
          </Box>
          <FormControl required fullWidth sx={{ marginTop: '1rem' }}>
            <InputLabel id="permission-label">Permissão</InputLabel>
            <Select
              labelId="permission-label"
              label="Permissão"
              value={permission}
              onChange={handleSelectPermission}
              sx={{textAlign: 'left'}}
            >
              {loggedUserInfo && Object.values(Permissions).filter(value => typeof value === 'number' && value <= loggedUserInfo.permission).map((p) => (
                <MenuItem key={p} value={String(p)}>
                  {PermissionLabels[p as Permissions]}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          {organizationCollection && <FormControl sx={{marginTop: '1rem'}} required fullWidth>
            <InputLabel id="org-select-label">Organização</InputLabel>
            <Select
              labelId="org-select-label"
              id="org-select"
              value={organizationId}
              label="Organização"
              onChange={handleSelectOrg}
              sx={{textAlign: 'left'}}
            >
              {organizationCollection.organizations && organizationCollection.organizations.map((org) =>
                (<MenuItem value={org.id}>{org.name}</MenuItem>))}
            </Select>
          </FormControl>}
          <Button
            variant="contained"
            size="large"
            fullWidth
            type="submit"
            sx={{ marginTop: '1rem' }}
            disabled={!organizationId || !username || !email || !firstName || !lastName}
          >
            Salvar
          </Button>
          <Alert
            severity="error"
            variant="outlined"
            sx={{ marginTop: '1rem', display: submitErrMsg ? 'flex' : 'none' }}
          >
            {submitErrMsg}
          </Alert>
        </>}
        <Alert
          severity="success"
          variant="outlined"
          sx={{ marginTop: '1rem', display: userCredentialMsg ? 'flex' : 'none' }}
        >
          {userCredentialMsg}
        </Alert>
      </Box>
      <Backdrop
        sx={{ color: '#fff', zIndex: (t) => t.zIndex.drawer + 1 }}
        open={isLoading}
      >
        <CircularProgress color="inherit" />
      </Backdrop>
    </FormPaper>
  );
};
